---
# handlers file for vector-role

- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: false
    name: vector.service
  when: vector_manage_service | default(true)
